#!/usr/bin/env python3
"""OpenClaw 配置管理服务 - 云端版"""
import json
import os
from pathlib import Path
from flask import Flask, jsonify, request, send_from_directory

app = Flask(__name__)

# 云端存储路径（Render 持久磁盘）
DATA_DIR = Path(os.environ.get('DATA_DIR', '.'))
UNIFIED_CONFIG = DATA_DIR / 'unified-config.json'

# Token 认证
SECRET_TOKEN = os.environ.get('SECRET_TOKEN', '')

def load_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def save_json(path, data):
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

def ensure_config_exists():
    """首次部署时创建默认配置"""
    if not UNIFIED_CONFIG.exists():
        DATA_DIR.mkdir(parents=True, exist_ok=True)
        default_config = {
            "active": "",
            "providers": {},
            "agents": []
        }
        save_json(UNIFIED_CONFIG, default_config)

ensure_config_exists()

@app.before_request
def check_auth():
    """Token 认证中间件"""
    # 首页和登录接口不需要认证
    if request.path in ('/', '/login'):
        return
    # 登录验证接口
    if request.path == '/api/auth':
        return
    # API 端点需要认证
    if request.path.startswith('/api'):
        if not SECRET_TOKEN:
            return  # 未设置 token 时跳过认证（本地开发用）
        token = request.headers.get('Authorization', '').replace('Bearer ', '')
        if not token:
            token = request.cookies.get('auth_token', '')
        if token != SECRET_TOKEN:
            return jsonify({'error': 'Unauthorized'}), 401

@app.route('/')
def index():
    return send_from_directory('.', 'config-ui-v2.html')

@app.route('/api/auth', methods=['POST'])
def auth():
    """验证 Token"""
    data = request.json
    token = data.get('token', '')
    if not SECRET_TOKEN or token == SECRET_TOKEN:
        return jsonify({'success': True})
    return jsonify({'success': False, 'message': '访问令牌错误'}), 401

@app.route('/api/unified-config', methods=['GET'])
def get_unified_config():
    """获取统一配置"""
    config = load_json(UNIFIED_CONFIG)
    return jsonify(config)

@app.route('/api/unified-config', methods=['POST'])
def update_unified_config():
    """更新统一配置"""
    data = request.json
    save_json(UNIFIED_CONFIG, data)
    return jsonify({'success': True})

@app.route('/api/switch-provider', methods=['POST'])
def switch_provider():
    """切换活跃提供商（带验证）"""
    data = request.json
    provider = data.get('provider')

    config = load_json(UNIFIED_CONFIG)

    if provider not in config['providers']:
        return jsonify({
            'success': False,
            'message': f'提供商 {provider} 不存在',
            'suggestion': '请检查配置或添加该提供商'
        }), 400

    provider_config = config['providers'][provider]
    if not provider_config.get('apiKey') or provider_config['apiKey'] == '':
        return jsonify({
            'success': False,
            'message': f'{provider_config["name"]} 的 API Key 未配置',
            'suggestion': '请先在配置编辑区域填写 API Key'
        }), 400

    old_active = config.get('active')
    config['active'] = provider
    save_json(UNIFIED_CONFIG, config)

    verify_config = load_json(UNIFIED_CONFIG)
    if verify_config.get('active') != provider:
        return jsonify({
            'success': False,
            'message': '配置文件保存失败',
            'suggestion': '请检查文件权限或磁盘空间'
        }), 500

    return jsonify({
        'success': True,
        'message': f'已从 {old_active} 切换到 {provider}',
        'provider': provider_config['name']
    })

@app.route('/api/env-exports', methods=['GET'])
def get_env_exports():
    """动态生成环境变量脚本"""
    config = load_json(UNIFIED_CONFIG)
    providers = config.get('providers', {})

    lines = [
        "# LLM Provider Environment Variables",
        "# Generated by OpenClaw Unified Config Manager",
        ""
    ]

    for provider_id, provider_config in providers.items():
        provider_upper = provider_id.upper()
        lines.append(f"# {provider_config['name']}")
        lines.append(f'export {provider_upper}_BASE_URL="{provider_config["baseUrl"]}"')
        lines.append(f'export {provider_upper}_API_KEY="{provider_config["apiKey"]}"')
        lines.append(f'export {provider_upper}_MODEL="{provider_config["defaultModel"]}"')
        lines.append("")

    active = config.get('active', '')
    lines.append(f'# Active Provider')
    lines.append(f'export LLM_PROVIDER="{active}"')
    lines.append("")

    return jsonify({'success': True, 'content': "\n".join(lines)})

@app.route('/api/agents', methods=['GET'])
def get_agents():
    """获取 agent 列表（从 unified-config.json 中读取）"""
    config = load_json(UNIFIED_CONFIG)
    agents = config.get('agents', [])
    return jsonify({
        'agents': agents,
        'providers': config.get('providers', {})
    })

@app.route('/api/update-agent-model', methods=['POST'])
def update_agent_model():
    """更新单个 agent 的模型配置"""
    data = request.json
    agent_id = data.get('agent_id')
    model_id = data.get('model_id')

    if '/' not in model_id:
        return jsonify({'success': False, 'message': '模型 ID 格式错误'}), 400

    config = load_json(UNIFIED_CONFIG)

    provider_id = model_id.split('/')[0]
    if provider_id not in config.get('providers', {}):
        return jsonify({'success': False, 'message': f'提供商 {provider_id} 不存在'}), 400

    agents = config.get('agents', [])
    agent_found = False
    for agent in agents:
        if agent['id'] == agent_id:
            agent['model'] = model_id
            agent_found = True
            break

    if not agent_found:
        return jsonify({'success': False, 'message': f'Agent {agent_id} 不存在'}), 400

    config['agents'] = agents
    save_json(UNIFIED_CONFIG, config)

    return jsonify({'success': True, 'message': f'已将 {agent_id} 的模型设置为 {model_id}'})

@app.route('/api/sync', methods=['POST'])
def sync_config():
    """云端版：返回当前配置（供本地 sync 脚本拉取）"""
    config = load_json(UNIFIED_CONFIG)
    return jsonify({
        'success': True,
        'message': '配置已就绪，请在本地运行 local-sync.py 同步',
        'config': config
    })

if __name__ == '__main__':
    app.run(host='127.0.0.1', port=8899, debug=True)
