#!/usr/bin/env python3
"""
从云端拉取统一配置并同步到本地 OpenClaw

用法:
  方式1: python3 local-sync.py
  方式2: curl -sH "Authorization: Bearer $TOKEN" $URL/api/unified-config | python3 local-sync.py

环境变量:
  CONFIG_CLOUD_URL - 云端服务地址 (如 https://your-app.onrender.com)
  CONFIG_TOKEN     - 访问令牌
"""
import json
import os
import sys
from pathlib import Path

HOME = Path.home()
OPENCLAW_DIR = HOME / ".openclaw"

def load_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def save_json(path, data):
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

def pull_from_cloud():
    """从云端 API 拉取配置"""
    import urllib.request
    url = os.environ.get('CONFIG_CLOUD_URL', '').rstrip('/')
    token = os.environ.get('CONFIG_TOKEN', '')

    if not url:
        print("错误: 请设置 CONFIG_CLOUD_URL 环境变量")
        sys.exit(1)

    req = urllib.request.Request(
        f'{url}/api/unified-config',
        headers={'Authorization': f'Bearer {token}'}
    )
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read().decode('utf-8'))

def generate_env_exports(providers, active):
    """生成环境变量导出脚本"""
    lines = [
        "# LLM Provider Environment Variables",
        "# Generated by OpenClaw Unified Config Manager",
        ""
    ]
    for provider_id, config in providers.items():
        provider_upper = provider_id.upper()
        lines.append(f"# {config['name']}")
        lines.append(f'export {provider_upper}_BASE_URL="{config["baseUrl"]}"')
        lines.append(f'export {provider_upper}_API_KEY="{config["apiKey"]}"')
        lines.append(f'export {provider_upper}_MODEL="{config["defaultModel"]}"')
        lines.append("")

    lines.append(f'# Active Provider')
    lines.append(f'export LLM_PROVIDER="{active}"')
    lines.append("")
    return "\n".join(lines)

def update_openclaw_config(unified, config_path):
    """更新 OpenClaw 配置文件"""
    if not config_path.exists():
        print(f"  跳过: {config_path} 不存在")
        return

    config = load_json(config_path)
    active = unified['active']
    active_config = unified['providers'][active]

    config['models']['providers'] = {}
    for provider_id, provider_config in unified['providers'].items():
        config['models']['providers'][provider_id] = {
            'baseUrl': provider_config['baseUrl'],
            'api': provider_config['api'],
            'models': provider_config['models']
        }

    model_id = f"{active}/{active_config['defaultModel']}"
    config['agents']['defaults']['model']['primary'] = model_id

    save_json(config_path, config)
    print(f"  已更新: {config_path}")

def update_auth_profiles(providers):
    """更新认证配置"""
    auth_path = OPENCLAW_DIR / "agents/main/agent/auth-profiles.json"
    if not auth_path.exists():
        print(f"  跳过: {auth_path} 不存在")
        return

    auth = load_json(auth_path)
    for provider_id, config in providers.items():
        profile_key = f"{provider_id}:default"
        if profile_key in auth['profiles']:
            auth['profiles'][profile_key]['key'] = config['apiKey']

    save_json(auth_path, auth)
    print(f"  已更新: {auth_path}")

def update_models_json(providers):
    """更新模型定义文件"""
    models_path = OPENCLAW_DIR / "agents/main/agent/models.json"
    models = {'providers': {}}

    for provider_id, config in providers.items():
        models['providers'][provider_id] = {
            'baseUrl': config['baseUrl'],
            'api': config['api'],
            'models': config['models'],
            'apiKey': config['apiKey']
        }

    save_json(models_path, models)
    print(f"  已更新: {models_path}")

def sync(unified):
    """执行完整本地同步"""
    providers = unified['providers']
    active = unified.get('active', '')

    print("1. 生成环境变量...")
    env_script = generate_env_exports(providers, active)
    env_path = OPENCLAW_DIR / "env-exports.sh"
    env_path.write_text(env_script)
    print(f"  已更新: {env_path}")

    print("2. 保存 unified-config.json...")
    unified_path = OPENCLAW_DIR / "unified-config.json"
    save_json(unified_path, unified)
    print(f"  已更新: {unified_path}")

    print("3. 更新 OpenClaw 配置...")
    update_openclaw_config(unified, OPENCLAW_DIR / "openclaw.json")
    sub1_path = HOME / ".openclaw-sub1" / "openclaw.json"
    if sub1_path.exists():
        update_openclaw_config(unified, sub1_path)

    print("4. 更新认证和模型...")
    update_auth_profiles(providers)
    update_models_json(providers)

    print("\n配置同步完成")

if __name__ == '__main__':
    # 支持两种输入方式
    if not sys.stdin.isatty():
        # 管道输入: curl ... | python3 local-sync.py
        unified = json.load(sys.stdin)
    else:
        # 直接运行: python3 local-sync.py（从云端拉取）
        unified = pull_from_cloud()

    sync(unified)
